name: linkify_plus
description: Turns text URLs and emails into clickable inline links in text for Flutter.
version: 5.0.5
homepage: https://github.com/Gaurav-CareMonitor/linkify_plus

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.13.8"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1 
  test: ^1.22.0
  flutter_test:
    sdk: flutter
